name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  node_version: 16
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.node_version}}
      - name: cache deps
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ env.node_version }}-node-modukes-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
